version: "2"

services:  
  
  monolithic:
    image: idugalic/monolithic
    ports:
     - "8080:8080"
    command: java -javaagent:kieker-1.15.4-aspectj.jar -Dspring.profiles.active=docker -jar /app.jar
 
